apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: watcher
  description: |
    Watcher is an open-source cloud stream Kafka consumer and publisher app.
  links:
    - title: SIT-Website
      url: http://google.com
    - title: Documentation
      url: https://sharepoint-link.com
  annotations:
    github.com/project-slug: SagarPrasad/watcher
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: website
  lifecycle: experimental
  owner: sagar
  providesApis:
    - watcher-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: watcher-api
spec:
  type: openapi
  lifecycle: experimental
  owner: sagar
  definition:
    $text: ./openapi.yaml
